apiVersion: v1
kind: Pod
metadata:
  name: basic-flask-postgres-db-pod
  labels:
    app: basic-flask-postgres-db
    model: give_me_some_credit
spec:
  containers:
    - name: basic-flask-postgres-db
      image: charlescazals/basic_flask_postgres_db
      ports:
        - containerPort: 5432 # informative only