apiVersion: v1
kind: Service
metadata:
  name: my-postgres-db
  labels:
    app: basic-flask-postgres-db
    model: give_me_some_credit
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: basic-flask-postgres-db
    model: give_me_some_credit