apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-flask-app-deployment
  labels:
    app: basic-flask-app
    model: give_me_some_credit
spec:
  replicas: 2
  template:
    metadata:
      name: basic-flask-pod
      labels:
        app: basic-flask-app
        model: give_me_some_credit
    spec:
      containers:
        - name: basic-flask
          image: charlescazals/basic_flask_app
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"

          ports:
            - containerPort: 5000 # informative only
  selector:
    matchLabels:
      app: basic-flask-app
      model: give_me_some_credit