apiVersion: v1
kind: Service
metadata:
  name: basic-flask-app-node-port
  labels:
    app: basic-flask-app
    model: give_me_some_credit
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 80
      # nodePort: gets automatically assigned (value 30000-32767)
  selector:
    app: basic-flask-app
    model: give_me_some_credit